# Given a list like myList=[1,2,3,4], your task is to find sum of each number with another number, i.e., 1+2,1+3,1+4,2+3,2+4,3+4 . Write two codes, one using list comprehension and other using for loop.

In [1]:
a = [1, 5, 4, 7]
#Defining a list a

In [2]:
#First Method
b = []

for i in range(len(a)):
    for j in range(i+1, len(a)):
        b.append(a[i]+a[j])

print("Result using for loop: \n", b)

In [3]:
#Second Method
c = [a[i]+a[j] for i in range(len(a)) for j in range(i+1, len(a))]

print("Result using list comprehension: \n", c)

# Given a list write a code to detect if there is a duplicate element present in the list (of integers) or not. Print yes or no. Write two codes, one using '==' operator and other using exclusive or operator '^'.

In [4]:
#https://thispointer.com/python-3-ways-to-check-if-there-are-duplicates-in-a-list/
def is_duplicate1(a):
    #Converting list a into set and checking the number of elements
    if len(a) == len(set(a)):
        print('no')
    else:
        print('yes')

In [5]:
def is_duplicate2(a):
    #Exclusive or (XOR) is true when both elements are different.
    if len(a) ^ len(set(a)):
        print('yes')
    else:
        print('no')

In [6]:
dup = [2, 3, 5, 2, 5]

In [7]:
#Checking for list a and b. List a has all unique values whereas list b has duplicates.
print("USING == OPERATOR\n\n")
print('For list a')
is_duplicate1(a)

print('For list dup')
is_duplicate1(dup)

USING == OPERATOR


For list a
no
For list dup
yes


In [8]:
#Checking for list a and b. List a has all unique values whereas list b has duplicates.
print("USING ^ OPERATOR\n\n")
print('For list a')
is_duplicate2(a)

print('For list dup')
is_duplicate2(dup)

USING ^ OPERATOR


For list a
no
For list dup
yes


# Given below is a 2D matrix, create a list of all the odd numbers present in the matrix. Also sort the list in descending order.
myMatrix = [[1, 2, 3, 4],
            [5, 6, 7],
            [8, 9, 10]]

In [9]:
myMatrix1 = [[1, 2, 3, 4],
            [5, 6, 7],
            [8, 9, 10]]

print(myMatrix1)

[[1, 2, 3, 4], [5, 6, 7], [8, 9, 10]]


In [10]:
Odd_numbers = []

for i in myMatrix1:
    for j in i:
        if j % 2 != 0:
            Odd_numbers.append(j)

print("List of odd numbers from matrix: ", Odd_numbers)
        
#Sorting the list
sorted_odd_no = sorted(Odd_numbers, reverse = True)
print("Sorted list of odd numbers from matrix: ", sorted_odd_no)

List of odd numbers from matrix:  [1, 3, 5, 7, 9]
Sorted list of odd numbers from matrix:  [9, 7, 5, 3, 1]


# Given below is a 2D matrix, create a list of squares of all the even numbers present in the matrix.
myMatrix = [[1, 2, 'aa',3, 4],
            ['dd',5, 6, 7],
            [8, 9, 10,'cc']]

In [11]:
myMatrix2 = [[1, 2, 'aa',3, 4],
            ['dd',5, 6, 7],
            [8, 9, 10,'cc']]

print(myMatrix2)

[[1, 2, 'aa', 3, 4], ['dd', 5, 6, 7], [8, 9, 10, 'cc']]


In [12]:
even_squared = []

for i in myMatrix2:
    for j in i:
        #Since there are multiple data types in the list, checking for integer data type
        if isinstance(j, int):
            if j % 2 == 0:
                even_squared.append(j**2)

print("List of even squared numbers: ", even_squared)

List of even squared numbers:  [4, 16, 36, 64, 100]


# Given below is a 2D matrix, create a list of squares of all the prime numbers present in the matrix. (Hint: use 6k+1 or 6k-1 formula)
myMatrix = [[21, 22, 23, 4, 16, 17, 18, 19],
            [5, 6, 7, 14, 15, 20, 1, 2, 3],
            [8, 9, 10, 11, 12, 13]]

In [13]:
myMatrix3 = [[21, 22, 23, 4, 16, 17, 18, 19],
            [5, 6, 7, 14, 15, 20, 1, 2, 3],
            [8, 9, 10, 11, 12, 13]]

print(myMatrix3)

[[21, 22, 23, 4, 16, 17, 18, 19], [5, 6, 7, 14, 15, 20, 1, 2, 3], [8, 9, 10, 11, 12, 13]]


In [14]:
#https://www.codecademy.com/forum_questions/54865f0f95e378f3fd000290
def checkPrime(n) : 
    
    #Checking the corner cases and middle cases(from 0 to 3 and their mutliples.)
    if n == 1 or n == 2 or n == 3:
        return True
    
    if n == 0 or n % 2 == 0 or n % 3 == 0:
        return False

    #Using 6k + 1
    i = 5
    #Increasing i by value 6 at every iteration.
    
    while(i * i <= n):
        
        if (n % i == 0 or n % (i + 2) == 0) : 
            return False
        
        i = i + 6
  
    return True

In [15]:
primes = []

for i in myMatrix3:
    for j in i:
        if checkPrime(j):
            primes.append(j**2)

print("List of squared prime numbers: ", primes)

List of squared prime numbers:  [529, 289, 361, 25, 49, 1, 4, 9, 121, 169]


# Make a dictionary of all those words, from the given paragraph, which are having 4 or more characters in it . Key of the dictionary should be word and value should be the number of times that word has appeared in the paragraph.  eg. {"feminist":3,"part":2,"campaign":1}
mySentence="It's the Spice Girls but not as you know them. Twenty years after it was first released, this famous girl power anthem has been given a 21st century feminist makeover. The new video is part of Project Everyone's campaign to improve the lives of women and girls everywhere, calling for an end to violence against girls, quality education for all and equal pay for equal work."

In [16]:
mySentence="It's the Spice Girls but not as you know them. Twenty years after it was first released, this famous girl power anthem has been given a 21st century feminist makeover. The new video is part of Project Everyone's campaign to improve the lives of women and girls everywhere, calling for an end to violence against girls, quality education for all and equal pay for equal work."

In [17]:
print(mySentence)

It's the Spice Girls but not as you know them. Twenty years after it was first released, this famous girl power anthem has been given a 21st century feminist makeover. The new video is part of Project Everyone's campaign to improve the lives of women and girls everywhere, calling for an end to violence against girls, quality education for all and equal pay for equal work.


In [18]:
#Getting all the words with 4 or more than 4 characters in a list #converting to lower case
List_of_words = [word.lower() for word in mySentence.split() if len(word) > 3]
print(List_of_words)

["it's", 'spice', 'girls', 'know', 'them.', 'twenty', 'years', 'after', 'first', 'released,', 'this', 'famous', 'girl', 'power', 'anthem', 'been', 'given', '21st', 'century', 'feminist', 'makeover.', 'video', 'part', 'project', "everyone's", 'campaign', 'improve', 'lives', 'women', 'girls', 'everywhere,', 'calling', 'violence', 'against', 'girls,', 'quality', 'education', 'equal', 'equal', 'work.']


In [19]:
#Counting the occurunces of these words and making a dictionary!
counts = {}

for word in List_of_words:
        if word not in counts :
            counts[word] = 0
        counts[word] += 1
    
#sorting
#counts = sorted(counts.items())
print(counts)

{"it's": 1, 'spice': 1, 'girls': 2, 'know': 1, 'them.': 1, 'twenty': 1, 'years': 1, 'after': 1, 'first': 1, 'released,': 1, 'this': 1, 'famous': 1, 'girl': 1, 'power': 1, 'anthem': 1, 'been': 1, 'given': 1, '21st': 1, 'century': 1, 'feminist': 1, 'makeover.': 1, 'video': 1, 'part': 1, 'project': 1, "everyone's": 1, 'campaign': 1, 'improve': 1, 'lives': 1, 'women': 1, 'everywhere,': 1, 'calling': 1, 'violence': 1, 'against': 1, 'girls,': 1, 'quality': 1, 'education': 1, 'equal': 2, 'work.': 1}


# Given a list, multiply all the elements of the list by 2 without using any arithmetic operator. Hint: use bitwise operator

In [20]:
#A bitwise left shift by 1 is equivalent to multiplying by 2 since binary has a base 2. 
#When we shift binary numbers by 1, we multiply by 2. When we shift base 10 numbers by 1, we multiply by 10.
#bitwise operations convert the number into binary and apply the operation on binary form hence, 2 multiplication.

list1 = [4 , 8, 3, 5, 7, 9]
print("Original list: \n", list1)

list2 = [a << 1 for a in list1]
print("\nList after 2 multiplication: \n", list2)

Original list: 
 [4, 8, 3, 5, 7, 9]

List after 2 multiplication: 
 [8, 16, 6, 10, 14, 18]


# Given below are two 2D matrix, add them element wise to form a third 2D matrix and print the resultant matrix.
myMatrix1 = [[1, 2, 3, 4],
            [5, 6, 7,6],
            [8, 9, 10,4]]

myMatrix2 = [[3, 1, 1, 4],
            [7, 7, 7,7],
            [8, 9, 10,11]]

In [21]:
myMatrix4 = [[1, 2, 3, 4],
            [5, 6, 7,6],
            [8, 9, 10,4]]

myMatrix5 = [[3, 1, 1, 4],
            [7, 7, 7,7],
            [8, 9, 10,11]]

print(myMatrix4)
print(myMatrix5)

[[1, 2, 3, 4], [5, 6, 7, 6], [8, 9, 10, 4]]
[[3, 1, 1, 4], [7, 7, 7, 7], [8, 9, 10, 11]]


In [22]:
import numpy as np
#Converting them into numpy arrays
M1 = np.asarray(myMatrix4)
M2 = np.asarray(myMatrix5)

In [23]:
M3 = M1 + M2
#By default numpy arrays perform element wise operations
print(M3)

[[ 4  3  4  8]
 [12 13 14 13]
 [16 18 20 15]]


In [24]:
#Can easily convert this into a list:
MyMatrix6 = M3.tolist()
print(MyMatrix6)

[[4, 3, 4, 8], [12, 13, 14, 13], [16, 18, 20, 15]]
